#!/bin/bash

#set -x

PARAMS=""
while (( "$#" )); do
  case "$1" in
    -a|--account-data)
      ACCOUNT_DATA_ARG=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
    -*|--*=)
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *)
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

eval set -- "$PARAMS"

if [ -z ${ACCOUNT_DATA_ARG+x} ]; then
  echo 'Must supply --account-data|-a argument with path to account data YAML file'
  exit 1
else
  ACCOUNT_DATA=$ACCOUNT_DATA_ARG
fi

RENDERED_TEMPLATE=infra-artifacts-repo-s3.yml

mkdir -p ../target

echo "Applying Jinja2 template to produce rendered CloudFormation template: ../target/${RENDERED_TEMPLATE}"

jinja2 ../infra-artifacts-repo-s3.yml.j2 ${ACCOUNT_DATA} --format=yml > ../target/${RENDERED_TEMPLATE}

echo "Executing cfn-lint to validate rendered template..."

cfn-lint ../target/${RENDERED_TEMPLATE}
